name: CI

on: [push]

jobs:
  PHPunit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Install composer dependencies
        run: composer install --prefer-dist

      - name: Run PHPUnit (PHP 7.4)
        run: php7.4 vendor/bin/phpunit

      - name: Run PHPUnit (PHP 7.3)
        run: php7.3 vendor/bin/phpunit

  php-cs-fixer:
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v1

        - name: Run php-cs-fixer
          uses: docker://oskarstark/php-cs-fixer-ga

        - uses: stefanzweifel/git-auto-commit-action@v2.1.0
          with:
            commit_message: Apply php-cs-fixer changes
            branch: ${{ github.ref }}
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}x