name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Install composer dependencies
        run: composer install --prefer-dist

      - name: Run PHPUnit (PHP 7.4)
        run: php7.4 vendor/bin/phpunit

      - name: Run PHPUnit (PHP 7.3)
        run: php7.3 vendor/bin/phpunit